name: Test and Deploy to Render

on:
  push:
    branches: [release]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mijn-api

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧪 Run tests
        env:
          ENVIRONMENT: production
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: 🚀 Trigger Render deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
