name: Test and Deploy to Render

on:
  push:
    branches: [release]  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        working-directory: ./mijn-api
        run: npm install

      - name: 🧪 Run tests
        working-directory: ./mijn-api
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: 🚀 Trigger Render deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
