name: Test and Deploy to Render

on:
  push:
    branches: [release]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        working-directory: mijn-api
        run: npm install

      - name: 🧪 Run tests
        working-directory: mijn-api
        env:
          ENVIRONMENT: production
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          chmod +x ./node_modules/.bin/mocha
          npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: 🚀 Trigger Render deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
